name: estesis_tech
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  logger: ^2.4.0
  intl: any
  get_it: ^7.7.0
  injectable: ^2.4.4
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  flutter_secure_storage: ^4.2.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_svg: ^2.0.10+1
  list_wheel_scroll_view_nls: ^0.0.3
  calendar_date_picker2: ^1.1.7
  envied: ^0.5.4+1
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  internet_connection_checker: ^2.0.0
  swipe_to: ^1.0.6

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.4.0
  injectable_generator: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
    - family: Poller One
      fonts:
        - asset: assets/fonts/poller_one/PollerOne-Regular.ttf
          weight: 400
